"""add_all_table

Revision ID: 4cd5c6774c2c
Revises: 
Create Date: 2026-01-28 10:16:59.383471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cd5c6774c2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mlmodel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('TRAINING', 'READY', 'DEPLOYED', 'FAILED', 'ARCHIVED', name='modelstatusenum'), nullable=False),
    sa.Column('auc_score', sa.Float(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('f1_score', sa.Float(), nullable=False),
    sa.Column('features', postgresql.ARRAY(sa.VARCHAR()), nullable=True),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('training_dataset_size', sa.Integer(), nullable=False),
    sa.Column('mlflow_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mlflow_experiment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mlflow_model_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('trained_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deployed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mlmodel_auc_score'), 'mlmodel', ['auc_score'], unique=False)
    op.create_index(op.f('ix_mlmodel_name'), 'mlmodel', ['name'], unique=False)
    op.create_index(op.f('ix_mlmodel_version'), 'mlmodel', ['version'], unique=False)
    op.create_table('permission',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_permission_code'), 'permission', ['code'], unique=False)
    op.create_table('role',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('trainingdataset',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('total_samples', sa.Integer(), nullable=False),
    sa.Column('fraud_samples', sa.Integer(), nullable=False),
    sa.Column('legitimate_samples', sa.Integer(), nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('dataset_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mlflow_artifact_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('feature_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('id_no', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('security_question', sa.Enum('MOTHER_MAIDEN_NAME', 'CHILDHOOD_FRIEND', 'FAVORITE_COLOR', 'BIRTH_CITY', name='securityquestionsschema'), nullable=False),
    sa.Column('security_answer', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('account_status', sa.Enum('ACTIVE', 'INACTIVE', 'LOCKED', 'PENDING', name='accountstatusschema'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('failed_login_attempts', sa.SMALLINT(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_failed_login', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('otp', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
    sa.Column('otp_expiry_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_no'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('bankaccount',
    sa.Column('account_type', sa.Enum('Current', 'Savings', 'FixedDeposit', 'Business', name='accounttypeenum'), nullable=False),
    sa.Column('currency', sa.Enum('VND', name='accountcurrencyenum'), nullable=False),
    sa.Column('account_status', sa.Enum('Active', 'Inactive', 'Pending', 'Closed', 'Frozen', name='accountstatusenum'), nullable=False),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('balance', sa.Numeric(scale=0), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('kyc_submitted', sa.Boolean(), nullable=False),
    sa.Column('kyc_verified', sa.Boolean(), nullable=False),
    sa.Column('kyc_verified_by', sa.Uuid(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('kyc_verified_on', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bankaccount_account_number'), 'bankaccount', ['account_number'], unique=True)
    op.create_table('idempotencykey',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotencykey_key'), 'idempotencykey', ['key'], unique=True)
    op.create_table('nextofkin',
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('relationship', sa.Enum('Spouse', 'Parent', 'Sibling', 'Child', 'Other', name='relationshiptypeenum'), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('passport_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('title', sa.Enum('Mr', 'Mrs', 'Miss', name='salutationenum'), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other', name='genderenum'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('country_of_birth', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('place_of_birth', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('marital_status', sa.Enum('Married', 'Divorced', 'Single', 'Widowed', name='maritalstatusenum'), nullable=False),
    sa.Column('means_of_identification', sa.Enum('Passport', 'Drivers_License', 'National_ID', name='identificationtypeenum'), nullable=False),
    sa.Column('id_issue_date', sa.Date(), nullable=False),
    sa.Column('id_expiry_date', sa.Date(), nullable=False),
    sa.Column('passport_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employment_status', sa.Enum('Employed', 'Unemployed', 'Self_Employed', 'Student', 'Retired', name='employmentstatusenum'), nullable=False),
    sa.Column('employer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employer_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employer_city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employer_country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('annual_income', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('date_of_employment', sa.Date(), nullable=False),
    sa.Column('profile_photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signature_photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratelimitlog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('request_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('window_start', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('window_end', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('blocked_until', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratelimitlog_ip_address'), 'ratelimitlog', ['ip_address'], unique=False)
    op.create_table('rolepermission',
    sa.Column('role_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('permission_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['permission_code'], ['permission.code'], ),
    sa.ForeignKeyConstraint(['role_code'], ['role.code'], ),
    sa.PrimaryKeyConstraint('role_code', 'permission_code')
    )
    op.create_table('userrole',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_code', sa.String(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_code'], ['role.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_code')
    )
    op.create_table('transaction',
    sa.Column('amount', sa.Numeric(scale=0), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_type', sa.Enum('Deposit', 'Withdrawal', 'Transfer', 'Reversal', 'Fee_Charged', 'Loan_Disbursement', 'Loan_Repayment', 'Interest_Credited', name='transactiontypeenum'), nullable=False),
    sa.Column('transaction_category', sa.Enum('Credit', 'Debit', name='transactioncategoryenum'), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Completed', 'Failed', 'Reversed', 'Cancelled', name='transactionstatusenum'), nullable=False),
    sa.Column('balance_before', sa.Numeric(scale=0), nullable=False),
    sa.Column('balance_after', sa.Numeric(scale=0), nullable=False),
    sa.Column('failed_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_review_status', sa.Enum('PENDING', 'FLAGGED', 'CLEARED', 'CONFIRMED_FRAUD', name='aireviewstatusenum'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_account_id', sa.Uuid(), nullable=True),
    sa.Column('receiver_account_id', sa.Uuid(), nullable=True),
    sa.Column('sender_id', sa.Uuid(), nullable=True),
    sa.Column('receiver_id', sa.Uuid(), nullable=True),
    sa.Column('processed_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('transaction_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['receiver_account_id'], ['bankaccount.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_account_id'], ['bankaccount.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_reference'), 'transaction', ['reference'], unique=True)
    op.create_table('virtualcard',
    sa.Column('card_type', sa.Enum('Debit', 'Credit', name='virtualcardtypeenum'), nullable=False),
    sa.Column('card_brand', sa.Enum('Visa', name='virtualcardbrandenum'), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'GBP', 'KES', 'VND', name='virtualcardcurrencyenum'), nullable=False),
    sa.Column('card_status', sa.Enum('Active', 'Inactive', 'Pending', 'Blocked', 'Expired', name='virtualcardstatusenum'), nullable=False),
    sa.Column('daily_limit', sa.Float(), nullable=False),
    sa.Column('monthly_limit', sa.Float(), nullable=False),
    sa.Column('name_on_card', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_physical_card_requested', sa.Boolean(), nullable=False),
    sa.Column('block_reason', sa.Enum('Lost', 'Stolen', 'Suspicious_Activity', 'Customer_Request', name='cardblockreasonenum'), nullable=True),
    sa.Column('block_reason_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('card_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('cvv_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('available_balance', sa.Float(), nullable=False),
    sa.Column('total_topped_up', sa.Float(), nullable=False),
    sa.Column('last_top_up_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('blocked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('total_spend_today', sa.Float(), nullable=False),
    sa.Column('total_spent_this_month', sa.Float(), nullable=False),
    sa.Column('last_transaction_date', sa.DateTime(), nullable=True),
    sa.Column('last_transaction_amount', sa.Float(), nullable=True),
    sa.Column('physical_card_requested_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('delivery_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('delivery_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('delivery_postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('physical_card_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('blocked_by', sa.Uuid(), nullable=True),
    sa.Column('card_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bank_account_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bankaccount.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocked_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelprediction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('prediction_score', sa.Float(), nullable=False),
    sa.Column('prediction_timestamp', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('input_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('true_label', sa.Boolean(), nullable=True),
    sa.Column('mlflow_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['mlmodel.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelprediction_model_id'), 'modelprediction', ['model_id'], unique=False)
    op.create_index(op.f('ix_modelprediction_transaction_id'), 'modelprediction', ['transaction_id'], unique=False)
    op.create_table('transactionriskscore',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('is_confirmed_fraud', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactionriskscore_risk_score'), 'transactionriskscore', ['risk_score'], unique=False)
    op.create_index(op.f('ix_transactionriskscore_transaction_id'), 'transactionriskscore', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactionriskscore_transaction_id'), table_name='transactionriskscore')
    op.drop_index(op.f('ix_transactionriskscore_risk_score'), table_name='transactionriskscore')
    op.drop_table('transactionriskscore')
    op.drop_index(op.f('ix_modelprediction_transaction_id'), table_name='modelprediction')
    op.drop_index(op.f('ix_modelprediction_model_id'), table_name='modelprediction')
    op.drop_table('modelprediction')
    op.drop_table('virtualcard')
    op.drop_index(op.f('ix_transaction_reference'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_table('userrole')
    op.drop_table('rolepermission')
    op.drop_index(op.f('ix_ratelimitlog_ip_address'), table_name='ratelimitlog')
    op.drop_table('ratelimitlog')
    op.drop_table('profile')
    op.drop_table('nextofkin')
    op.drop_index(op.f('ix_idempotencykey_key'), table_name='idempotencykey')
    op.drop_table('idempotencykey')
    op.drop_index(op.f('ix_bankaccount_account_number'), table_name='bankaccount')
    op.drop_table('bankaccount')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('trainingdataset')
    op.drop_table('role')
    op.drop_index(op.f('ix_permission_code'), table_name='permission')
    op.drop_table('permission')
    op.drop_index(op.f('ix_mlmodel_version'), table_name='mlmodel')
    op.drop_index(op.f('ix_mlmodel_name'), table_name='mlmodel')
    op.drop_index(op.f('ix_mlmodel_auc_score'), table_name='mlmodel')
    op.drop_table('mlmodel')
    # ### end Alembic commands ###
