"""add_risk_score_model

Revision ID: 9278368f0dac
Revises: c431487c1ac9
Create Date: 2026-01-07 01:51:41.791788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9278368f0dac'
down_revision: Union[str, None] = 'c431487c1ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
          CREATE TYPE aireviewstatusenum AS ENUM (
            'PENDING',
            'FLAGGED',
            'CLEARED',
            'CONFIRMED_FRAUD'
          );
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction",
        sa.Column(
            "ai_review_status",
            sa.Enum(
                "PENDING",
                "FLAGGED",
                "CLEARED",
                "CONFIRMED_FRAUD",
                name="aireviewstatusenum",
                create_type=False,
            ),
            nullable=True,
        ),
    )
    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "ai_review_status")

    op.execute("DROP TYPE aireviewstatusenum;")
    # ### end Alembic commands ###
