"""add_ratelimit_log_table

Revision ID: c431487c1ac9
Revises: c2eca12022e0
Create Date: 2026-01-06 09:55:32.230827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c431487c1ac9'
down_revision: Union[str, None] = 'c2eca12022e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratelimitlog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('request_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('window_start', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('window_end', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('blocked_until', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratelimitlog_ip_address'), 'ratelimitlog', ['ip_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratelimitlog_ip_address'), table_name='ratelimitlog')
    op.drop_table('ratelimitlog')
    # ### end Alembic commands ###
